#!/usr/bin/env python3
"""
Emergency Risk Control Script
Immediately reduces risk exposure to prevent further losses
"""

import json
import os
import sys
import time
import requests
import hmac
import hashlib
from datetime import datetime

# Configuration
BINANCE_TESTNET_URL = "https://testnet.binancefuture.com"
API_KEY = os.getenv("BINANCE_API_KEY")
API_SECRET = os.getenv("BINANCE_API_SECRET")

# Emergency Risk Parameters
EMERGENCY_LEVERAGE = 10  # Reduced from 40x
EMERGENCY_MAX_POSITIONS = 3  # Drastically reduced
EMERGENCY_POSITION_CAP = 15  # Reduced from $50

def make_hmac_hash(params_str):
    return hmac.new(API_SECRET.encode(), params_str.encode(), hashlib.sha256).hexdigest()

def close_all_positions():
    """Close all open positions to stop losses"""
    print(f"[{datetime.now()}] EMERGENCY: Closing all positions...")
    
    # Get account information
    endpoint = "/fapi/v2/account"
    timestamp = int(time.time() * 1000)
    params_str = f"timestamp={timestamp}"
    signature = make_hmac_hash(params_str)
    
    response = requests.get(
        f"{BINANCE_TESTNET_URL}{endpoint}?{params_str}&signature={signature}",
        headers={"X-MBX-APIKEY": API_KEY}
    )
    
    if response.status_code != 200:
        print(f"ERROR: Failed to get account info: {response.status_code}")
        return False
        
    account_data = response.json()
    positions = account_data.get("positions", [])
    
    # Close all open positions
    for position in positions:
        position_size = float(position.get("positionAmt", 0))
        if abs(position_size) > 0.001:  # Only close non-zero positions
            symbol = position["symbol"]
            # Determine closing side
            side = "sell" if position_size > 0 else "buy"
            
            print(f"Closing position: {symbol} ({abs(position_size)} units)")
            
            # Place closing order
            close_order(symbol, abs(position_size), side)
    
    return True

def close_order(symbol, quantity, side):
    """Place closing order"""
    endpoint = "/fapi/v1/order"
    timestamp = int(time.time() * 1000)
    params_str = f"symbol={symbol}&side={side}&type=MARKET&quantity={quantity}&timestamp={timestamp}"
    signature = make_hmac_hash(params_str)
    
    response = requests.post(
        f"{BINANCE_TESTNET_URL}{endpoint}?{params_str}&signature={signature}",
        headers={"X-MBX-APIKEY": API_KEY},
        params=None # Ensure no duplicate params in body
    )
    
    if response.status_code == 200:
        print(f"SUCCESS: Placed closing order for {symbol}")
        return True
    else:
        print(f"ERROR: Failed to close {symbol}: {response.status_code}")
        return False

def update_risk_config():
    """Update configuration files with emergency risk parameters"""
    config_path = "/home/nkhekhe/unified_trading_system/config/unified.yaml"
    
    if not os.path.exists(config_path):
        create_emergency_config(config_path)
        return
        
    try:
        with open(config_path, 'r') as f:
            config_data = f.read()
        
        # Save backup
        with open(f"{config_path}.backup_{int(time.time())}", 'w') as f:
            f.write(config_data)
        
        # Update risk parameters
        print(f"[{datetime.now()}] EMERGENCY: Updating risk configuration...")
        
        # Create new config with emergency parameters
        emergency_config = f"""
# EMERGENCY RISK CONFIGURATION
# Generated by emergency_risk_control.py

system:
  name: "Unified Trading System"
  version: "1.0.0"
  environment: "development"
  debug: false
  log_level: "INFO"

# EMERGENCY RISK PARAMETERS - REDUCED FOR CAPITAL PRESERVATION
risk_management:
  emergency: true
  max_leverage: {EMERGENCY_LEVERAGE}
  max_positions: {EMERGENCY_MAX_POSITIONS}
  max_position_size: {EMERGENCY_POSITION_CAP}
  position_size_pct: 0.1  # 10% of balance
  leverage_decrease_factor: 0.25  # 75% reduction
  daily_loss_limit: 0.02  # 2% daily loss limit
  
  risk_manifold:
    drawdown_warning: 0.03  # 3%
    drawdown_danger: 0.05   # 5%
    drawdown_critical: 0.07 # 7%
    max_leverage: {EMERGENCY_LEVERAGE}
    
  safety_governor:
    max_position_pct: 0.05  # 5% max position
    max_portfolio_pct: 0.15 # 15% max portfolio exposure
"""
        
        with open(config_path, 'w') as f:
            f.write(emergency_config)
            
        print("SUCCESS: Emergency configuration applied")
        return True
        
    except Exception as e:
        print(f"ERROR: Failed to update config: {e}")
        return False

def create_emergency_config(config_path):
    """Create emergency config if none exists"""
    print(f"[{datetime.now()}] EMERGENCY: Creating emergency config file...")
    
    try:
        os.makedirs(os.path.dirname(config_path), exist_ok=True)
        
        emergency_config = f"""
# EMERGENCY RISK CONFIGURATION
# Generated by emergency_risk_control.py

system:
  name: "Unified Trading System"
  version: "1.0.0"
  environment: "development"
  debug: false
  log_level: "INFO"

# EMERGENCY RISK PARAMETERS
risk_management:
  emergency: true
  max_leverage: {EMERGENCY_LEVERAGE}
  max_positions: {EMERGENCY_MAX_POSITIONS}
  max_position_size: {EMERGENCY_POSITION_CAP}
  position_size_pct: 0.1
  leverage_decrease_factor: 0.25
  daily_loss_limit: 0.02

  risk_manifold:
    drawdown_warning: 0.03
    drawdown_danger: 0.05
    drawdown_critical: 0.07
    max_leverage: {EMERGENCY_LEVERAGE}
    
  safety_governor:
    max_position_pct: 0.05
    max_portfolio_pct: 0.15
"""
        
        with open(config_path, 'w') as f:
            f.write(emergency_config)
            
        print("SUCCESS: Emergency configuration created")
        return True
        
    except Exception as e:
        print(f"ERROR: Failed to create config: {e}")
        return False

def kill_trading_process():
    """Kill the current trading process"""
    try:
        # Find the trading process
        result = os.popen("ps aux | grep continuous_trading_loop_binance.py | grep -v grep").read()
        
        if result.strip():
            pid = result.split()[1]
            print(f"[{datetime.now()}] EMERGENCY: Killing trading process PID: {pid}")
            os.kill(int(pid), 9)
            return True
        else:
            print("WARNING: Trading process not found")
            return False
            
    except Exception as e:
        print(f"ERROR: Failed to kill process: {e}")
        return False

def main():
    print("=" * 60)
    print("EMERGENCY RISK CONTROL ACTIVATED")
    print(f"Timestamp: {datetime.now()}")
    print("=" * 60)
    
    # Step 1: Kill current trading process
    kill_trading_process()
    time.sleep(2)
    
    # Step 2: Close all positions
    close_all_positions()
    time.sleep(5)
    
    # Step 3: Update configuration with emergency parameters
    update_risk_config()
    
    print("=" * 60)
    print("EMERGENCY PROCEDURES COMPLETED")
    print("System now in safe mode with reduced risk parameters")
    print("=" * 60)
    
    return True

if __name__ == "__main__":
    main()